banner:
  location: banner.txt

spring:
  profiles.active: default

  resources:
    static-locations: file:/root/web-client-v1/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
server:
  port: 8080


logging:
  file: /root/web-client-v1/log/web-client-v1.log
  # LEVEL: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
  level:
    com.bq.i1: INFO

i1:
  adapter:
    url: http://localhost:8081
  i1-adapter:
    url: http://localhost:8082
  tiptop-adapter:
    url: http://localhost:8083
  ec-adapter:
    url: http://localhost:8084
  tmall-adapter:
    url: http://localhost:8085



--- # default profile
spring:
  profiles: default


--- # SIT
banner:
  location: banner-sit.txt

i1:
  adapter:
    url: http://project.benchmarkchian.com:18011
  i1-adapter:
    url: http://project.benchmarkchian.com:18012
  tiptop-adapter:
    url: http://project.benchmarkchian.com:18013
  ec-adapter:
    url: http://project.benchmarkchian.com:18014
  tmall-adapter:
    url: http://project.benchmarkchian.com:18015

--- # UAT
banner:
  location: banner-uat.txt

i1:
  adapter:
    url: http://project.benchmarkchian.com:18021
  i1-adapter:
    url: http://project.benchmarkchian.com:18022
  tiptop-adapter:
    url: http://project.benchmarkchian.com:18023
  ec-adapter:
    url: http://project.benchmarkchian.com:18024
  tmall-adapter:
    url: http://project.benchmarkchian.com:18025

--- # Kent's Dev

spring:

  profiles: kent

i1:
  i1-server:
    url: http://localhost:8081
  i1-adapter:
    url: http://localhost:8082

--- # Ethan's Dev

spring:

  profiles: ethan

i1:
  i1-server:
    url: http://localhost:8081
  i1-adapter:
    url: http://localhost:8082



