banner:
  location: banner.txt

spring:
  profiles.active: default

  resources:
    static-locations: file:/root/web-client-v1/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
server:
  port: 8080


logging:
  file: /root/web-client-v1/log/web-client-v1.log
  # LEVEL: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
  level:
    com.bq.i1: INFO

i1:
  i1-server:
    url: http://localhost:8081
  i1-adapter:
    url: http://localhost:8082
  tiptop-adapter:
    url: http://localhost:8083
  ec-adapter:
    url: http://localhost:8084
  tmall-adapter:
    url: http://localhost:8085


--- # default profile
spring:
  profiles: default


--- # SIT

banner:
  location: banner-sit.txt

spring:
  profiles: SIT


i1:
  i1-server:
    url: http://project.benchmarkchina.com:10811
  i1-adapter:
    url: http://project.benchmarkchina.com:10812
  tiptop-adapter:
    url: http://project.benchmarkchina.com:10813
  ec-adapter:
    url: http://project.benchmarkchina.com:10041
  tmall-adapter:
    url: http://project.benchmarkchina.com:10815


--- # DEV

banner:
  location: banner-dev.txt

spring:
  profiles: DEV


--- # Kent's Dev

spring:

  profiles: kent


--- # Ethan's Dev

spring:

  profiles: ethan


--- # Xavier's Dev

spring:

  profiles: xavier

i1:
  i1-server:
    url: http://project.benchmarkchina.com:10811
  i1-adapter:
    url: http://project.benchmarkchina.com:10812
  tiptop-adapter:
    url: http://project.benchmarkchina.com:10813
  ec-adapter:
    url: http://project.benchmarkchina.com:10041
  tmall-adapter:
    url: http://project.benchmarkchina.com:10815


--- # Ruka's Dev

spring:

  profiles: ruka

i1:
  i1-server:
    url: http://10.10.80.22:8081
#    url: http://project.benchmarkchina.com:10811
  i1-adapter:
    url: http://project.benchmarkchina.com:10812
  tiptop-adapter:
    url: http://project.benchmarkchina.com:10813
  ec-adapter:
    url: http://project.benchmarkchina.com:10814
  tmall-adapter:
    url: http://project.benchmarkchina.com:10815

--- # GuJian's Dev

spring:

  profiles: gujian

i1:
  i1-server:
    #url: http://project.benchmarkchina.com:10811
    url: http://localhost:8081
  i1-adapter:
    #url: http://project.benchmarkchina.com:10812
    url: http://localhost:8082
  tiptop-adapter:
    #url: http://project.benchmarkchina.com:10813
    url: http://localhost:8083
  ec-adapter:
    #url: http://project.benchmarkchina.com:10814
    url: http://localhost:8084
  tmall-adapter:
    url: http://project.benchmarkchina.com:10815


--- # Chris Dev

spring:

  profiles: junea

i1:
  i1-server:
    #url: http://project.benchmarkchina.com:50001
    url: http://localhost:8081
  i1-adapter:
    #url: http://project.benchmarkchina.com:10812
    url: http://localhost:8082
  tiptop-adapter:
    #url: http://project.benchmarkchina.com:10813
    url: http://localhost:8083
  ec-adapter:
    url: http://project.benchmarkchina.com:10814
    #url: http://localhost:8084
  tmall-adapter:
    url: http://project.benchmarkchina.com:10815

--- # Carzy Dev

spring:

profiles: carzy

i1:
  i1-server:
    #url: http://project.benchmarkchina.com:10811
    url: http://localhost:8081
  i1-adapter:
    #url: http://project.benchmarkchina.com:10812
    url: http://localhost:8082
  tiptop-adapter:
    #url: http://project.benchmarkchina.com:10813
    url: http://localhost:8083
  ec-adapter:
    url: http://project.benchmarkchina.com:10814
    #url: http://localhost:8084
  tmall-adapter:
    url: http://project.benchmarkchina.com:10815


--- # rain's Dev

spring:

  profiles: rain

i1:
  i1-server:
    #url: http://project.benchmarkchina.com:10811
    url: http://localhost:8081
  i1-adapter:
    url: http://project.benchmarkchina.com:10812
  tiptop-adapter:
    url: http://project.benchmarkchina.com:10813
  ec-adapter:
    url: http://project.benchmarkchina.com:10041
    #url: http://localhost:8084
  tmall-adapter:
    url: http://project.benchmarkchina.com:10815

--- # xavier's Dev

spring:
  profiles: xavier

i1:
  i1-server:
    url: http://localhost:8081
  i1-adapter:
    url: http://project.benchmarkchina.com:10812
  tiptop-adapter:
    url: http://project.benchmarkchina.com:10813
  ec-adapter:
#    url: http://project.benchmarkchina.com:10041
    url: http://localhost:8084
  tmall-adapter:
    url: http://project.benchmarkchina.com:10815


